[gcp_service_account]
type = "service_account"
project_id = "semaforo-direccion"
private_key_id = "c20318ce5a608831f493354efe22259e52d1ba9d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCnE/k3snRWnet
de9dbgys8VZujkpm6LBo0zSMOLBLDMYBOBxE517a+NL/oUMr6YFgZwMDAJOqm3ji
qkxzAxZ9LHKBsOL0Odyamb2q2JHZOEkLb5NmGHUSkDpCrD4InmhnDTcUim/ReW7S
3Rkizx9Y2pSFJJaZExj3qCtF/Dl3CFE7ansi8MTEWghk0PF5w7E+7+rkyTKfnrMG
W91n+9mYsoVaBL1EEXVN/wFIzwpvMGKZ2z6rlPuP3U/RJSMU0deoXI+wweJbl/Wh
yWlQbfYjmrFpfVoOTLdOwdFn5ry6wUHdL40/jQV/bE7sZBcUpj9pmtGAgjechiOd
1I4PCxShAgMBAAECggEADxqvrr1F36xMVpetLMyySifvA+SiTKtpqbEexnVN5X1H
zudqdkSY3ZjrU3DSNFHKu08zciO00kx/zOPXzCNktvFgr8UpUDg/cXZWPLDTXQ8b
yDnwMD/cskSkaPFSXTviMYFakYsPE6x/l/kWDtgRgEVyuoS09YuAaBRSy3tAgIbv
irFVOFO535sVepVIvZze/hxdfK8pvVWbG2YL5VabgVTj4x0m/DHXBS0kJi1Q9YSh
53oO2LjBKS0vvRbD2tRAld4KcPiqE/UiRL8t75W/QH/NcDbIuS7eI9wLsrv2gkMG
/q/X32rPSmwIXVBoIJJOEfnflPFdGqnMv+cq2QdzOQKBgQDqZRM3WlQVXyb9AwID
5ODt/D+nQYbKv2BwQezLGXOq3lHSpZc92rz7SdNf1eoUkUjvqD8YmCUyfZlQ2sZc
DQA9eQryG2PrEUWKX+hPkube/AmTiGus2xbdB7cx2oX/7tceU4hZMvekpclsrIvY
d1a1GuY9Z9RROFy0p/GgabnUlQKBgQDUjHa5mLOGSOQsl0uNYd8VWTfSPkqQHUZ3
qcbbLUOd4iSk6hOnqEz97bcm+0ndI2d9m6yw2EttrUMrdvyQCoGIXLwSWMpY/59i
4i5FdpRPYpmzdQA3J4EUJQ9TfZdu5o/pHqlDiZeh9u/Sp6+Bh0UW/SZLbh20QwzM
6kO5XnBQ3QKBgG3Mo0/OtIy+Yhkri4ofcW6KN5c2DtpzA84SU8ZgSdrFAjdW8p47
FUPxtV6zak/wLuZ1PflbbDFWvLcvhLQiMvaY+ROo2QmIsba8bqq3+gaCskm2Ihp7
Fx67OonT/+mADK1cHAcM5QzvzIdn3KquXKPB0hD5zm+to1/NPFcUr8RxAoGBAIfM
ds590bWqPJ6Ay7S5I17wccnSIrGRAsTRpEvEz77ADcmQBJ7J2OckSjCNvNOdGzIV
lHAowYiBerj6fMNK8xe8qCzQrffO2nbDK+0VpgxSYwFVb53Nj5rfUrt1MpuYk7nN
7TdJYagJrZBZsrh/RJU7iIwI/tF9RWBnDH4S6I/BAoGBAOXW8M+WcyQOVoQ/ejts
kRfYhEXo0KYtmXQHfBQq5bHN3P8nfqt72JFgpZPy9QyUzdmCsIjRbdKOwWXXj29H
ZsKdnh4YcuZcB1FFXkWw9AMZq7RJF37Er0wUJ/6AdKzBtdFrpkcf9yhG37YNLzz4
Ff5+GLfmBPm+zb8cIE4u7K2K
-----END PRIVATE KEY-----"""
client_email = "streamlit-drive-access@semaforo-direccion.iam.gserviceaccount.com"
client_id = "114317562306900148059"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-drive-access%40semaforo-direccion.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
